background = #08060A
foreground = #F4F1EA

palette = 0=#08060A
palette = 1=#E34B4B
palette = 2=#7FAF62
palette = 3=#FFB52E
palette = 4=#7950A3
palette = 5=#B34BD1
palette = 6=#63B7B0
palette = 7=#F4F1EA

palette = 8=#746775
palette = 9=#FF665E
palette = 10=#9CCE72
palette = 11=#FFD05A
palette = 12=#9A6CC4
palette = 13=#D56AF2
palette = 14=#82D8CE
palette = 15=#FFFFFF
