# Background and foreground colors
background = #000000
foreground = #C8CED9

# Standard colors
palette = 0=#000000
palette = 1=#978caf
palette = 2=#98c7e4
palette = 3=#b9f9ff
palette = 4=#6e7ca1
palette = 5=#a3a4d4
palette = 6=#aedcff
palette = 7=#C8CED9

# Bright colors
palette = 8=#686163
palette = 9=#aea0cc
palette = 10=#a1dfff
palette = 11=#aeffff
palette = 12=#8091be
palette = 13=#b7b8f6
palette = 14=#bbf4ff
palette = 15=#f1f5ff
