$color = rgba(0, 0, 0, 1)
$inner_color = rgba(0, 0, 0, 0.66)
$outer_color = rgba(163, 164, 212, 1)
$font_color = rgba(200, 206, 217, 1)
$placeholder_color = rgba(200, 206, 217, 0.7)
$check_color = rgba(174, 220, 255, 1)
