background            #000000
foreground            #C8CED9

# black
color0  #000000
color8  #686163

# red
color1  #978caf
color9  #aea0cc

# green
color2  #98c7e4
color10 #a1dfff

# yellow
color3  #b9f9ff
color11 #aeffff

# blue
color4  #6e7ca1
color12 #8091be

# magenta
color5  #a3a4d4
color13 #b7b8f6

#cyan
color6  #aedcff
color14 #bbf4ff

#white
color7  #C8CED9
color15 #f1f5ff
