background = 0xFF0C2340
base = 0xFF111827
text = 0xFFFFFFFF
alternate_base = 0xFF1D3557
bright_text = 0xFFFFFFFF

accent = 0xFF003594
accent_secondary = 0xFF869397

font_size = 13
small_font_size = 11
h1_size = 20
h2_size = 16
h3_size = 14

rounding_large = 12
rounding_small = 7
