background = 1A100A
foreground = FFF3DF

palette = 0=#1A100A
palette = 1=#B84A32
palette = 2=#7F8A48
palette = 3=#D9A441
palette = 4=#6B7D87
palette = 5=#9A5A4A
palette = 6=#73958B
palette = 7=#FFF3DF
palette = 8=#8C7765
palette = 9=#D76343
palette = 10=#9AA85B
palette = 11=#F0C15A
palette = 12=#879AA5
palette = 13=#B87562
palette = 14=#8EB1A6
palette = 15=#FFFFFF
